// Simulated Demo Data

export const COMPANIES = [
  { id: '1', name: 'TechCorp Solutions', industry: 'Technology', city: 'San Francisco', state: 'CA', description: 'Leading software development company', logoUrl: null, website: 'https://techcorp.io' },
  { id: '2', name: 'FinanceHub Inc', industry: 'Finance', city: 'New York', state: 'NY', description: 'Modern fintech company', logoUrl: null, website: 'https://financehub.com' },
  { id: '3', name: 'HealthFirst Medical', industry: 'Healthcare', city: 'Boston', state: 'MA', description: 'Patient-centered healthcare', logoUrl: null, website: 'https://healthfirst.org' },
  { id: '4', name: 'RetailMax', industry: 'Retail', city: 'Chicago', state: 'IL', description: 'Omnichannel retail leader', logoUrl: null, website: 'https://retailmax.com' },
  { id: '5', name: 'EduLearn Academy', industry: 'Education', city: 'Austin', state: 'TX', description: 'Online learning platform', logoUrl: null, website: 'https://edulearn.edu' },
  { id: '6', name: 'GreenEnergy Co', industry: 'Energy', city: 'Denver', state: 'CO', description: 'Sustainable energy solutions', logoUrl: null, website: 'https://greenenergy.co' },
  { id: '7', name: 'MediaWorks Studio', industry: 'Media', city: 'Los Angeles', state: 'CA', description: 'Creative agency', logoUrl: null, website: 'https://mediaworks.studio' },
  { id: '8', name: 'LogiTech Systems', industry: 'Technology', city: 'Seattle', state: 'WA', description: 'Supply chain software', logoUrl: null, website: 'https://logitechsys.com' }
]

export const JOBS = [
  { id: '1', companyId: '1', title: 'Senior Full Stack Developer', description: 'We are looking for an experienced full stack developer to join our engineering team.', requirements: ['5+ years experience', 'React/Node.js', 'Database design'], responsibilities: ['Build web applications', 'Collaborate with teams', 'Mentor junior devs'], jobType: 'FULL_TIME', location: 'San Francisco, CA', salaryMin: 120000, salaryMax: 180000, experienceRequired: 5, skillsRequired: ['react', 'nodejs', 'postgresql', 'typescript'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '2', companyId: '2', title: 'Financial Analyst', description: 'Join our finance team to analyze market trends.', requirements: ['MBA or equivalent', '3+ years finance', 'Excel'], responsibilities: ['Analyze financial data', 'Prepare reports'], jobType: 'FULL_TIME', location: 'New York, NY', salaryMin: 85000, salaryMax: 120000, experienceRequired: 3, skillsRequired: ['excel', 'financial-analysis', 'sql'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '3', companyId: '3', title: 'Registered Nurse', description: 'Provide exceptional patient care.', requirements: ['RN license', 'BLS', '2+ years'], responsibilities: ['Patient assessment', 'Medication'], jobType: 'FULL_TIME', location: 'Boston, MA', salaryMin: 75000, salaryMax: 95000, experienceRequired: 2, skillsRequired: ['patient-care', 'medical-software'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '4', companyId: '4', title: 'Marketing Manager', description: 'Lead our marketing initiatives.', requirements: ['Marketing degree', '5+ years'], responsibilities: ['Develop strategies', 'Manage campaigns'], jobType: 'FULL_TIME', location: 'Chicago, IL', salaryMin: 90000, salaryMax: 130000, experienceRequired: 5, skillsRequired: ['digital-marketing', 'seo', 'analytics'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '5', companyId: '5', title: 'Online Instructor', description: 'Teach data science courses.', requirements: ['Masters', 'Python'], responsibilities: ['Create content', 'Conduct sessions'], jobType: 'CONTRACT', location: 'Remote', salaryMin: 60000, salaryMax: 90000, experienceRequired: 3, skillsRequired: ['python', 'machine-learning'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '6', companyId: '6', title: 'Sales Representative', description: 'Drive revenue growth.', requirements: ['Sales experience', 'CRM'], responsibilities: ['Prospect clients', 'Maintain relationships'], jobType: 'FULL_TIME', location: 'Denver, CO', salaryMin: 50000, salaryMax: 80000, experienceRequired: 2, skillsRequired: ['sales', 'crm', 'negotiation'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '7', companyId: '7', title: 'Content Creator', description: 'Create engaging content.', requirements: ['Portfolio', 'Video editing'], responsibilities: ['Create content', 'Manage social'], jobType: 'PART_TIME', location: 'Los Angeles, CA', salaryMin: 45000, salaryMax: 65000, experienceRequired: 2, skillsRequired: ['video-editing', 'content-creation'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '8', companyId: '1', title: 'DevOps Engineer', description: 'Build cloud infrastructure.', requirements: ['AWS', 'CI/CD'], responsibilities: ['Manage cloud', 'Implement CI/CD'], jobType: 'FULL_TIME', location: 'Seattle, WA', salaryMin: 110000, salaryMax: 160000, experienceRequired: 4, skillsRequired: ['aws', 'docker', 'kubernetes'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '9', companyId: '8', title: 'UX Designer', description: 'Design intuitive experiences.', requirements: ['Figma', 'User research'], responsibilities: ['User research', 'Wireframes'], jobType: 'FULL_TIME', location: 'San Francisco, CA', salaryMin: 95000, salaryMax: 140000, experienceRequired: 3, skillsRequired: ['figma', 'user-research'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '10', companyId: '2', title: 'Data Engineer', description: 'Build data pipelines.', requirements: ['SQL', 'Python'], responsibilities: ['Build pipelines', 'Design models'], jobType: 'FULL_TIME', location: 'New York, NY', salaryMin: 115000, salaryMax: 155000, experienceRequired: 4, skillsRequired: ['python', 'sql', 'spark'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '11', companyId: '3', title: 'HR Coordinator', description: 'Support HR operations.', requirements: ['HR degree', '2+ years'], responsibilities: ['Onboarding', 'Benefits'], jobType: 'FULL_TIME', location: 'Chicago, IL', salaryMin: 50000, salaryMax: 65000, experienceRequired: 2, skillsRequired: ['hris', 'recruiting'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null },
  { id: '12', companyId: '5', title: 'Frontend Developer - React', description: 'Build beautiful UIs.', requirements: ['React', 'CSS'], responsibilities: ['Build components', 'Implement designs'], jobType: 'FULL_TIME', location: 'San Francisco, CA', salaryMin: 100000, salaryMax: 145000, experienceRequired: 3, skillsRequired: ['react', 'typescript', 'css'], status: 'ACTIVE', createdAt: new Date().toISOString(), deadline: null }
]

export const CANDIDATES = [
  { id: '1', fullName: 'Alice Johnson', email: 'alice@example.com', phone: '555-0101', city: 'San Francisco', state: 'CA', bio: 'Passionate software engineer with 6 years experience.', skills: ['react', 'nodejs', 'typescript'], experienceYears: 6, education: 'BS CS, Stanford 2018', profilePhotoUrl: null },
  { id: '2', fullName: 'Bob Smith', email: 'bob@example.com', phone: '555-0102', city: 'New York', state: 'NY', bio: 'Data-driven financial analyst.', skills: ['python', 'sql', 'excel'], experienceYears: 4, education: 'MBA Finance, NYU 2020', profilePhotoUrl: null },
  { id: '3', fullName: 'Carol Williams', email: 'carol@example.com', phone: '555-0103', city: 'Boston', state: 'MA', bio: 'Dedicated healthcare professional.', skills: ['patient-care', 'medical-software'], experienceYears: 5, education: 'BS Nursing, Boston College 2019', profilePhotoUrl: null },
  { id: '4', fullName: 'David Brown', email: 'david@example.com', phone: '555-0104', city: 'Chicago', state: 'IL', bio: 'Creative marketer.', skills: ['digital-marketing', 'seo'], experienceYears: 7, education: 'BA Marketing, Northwestern 2017', profilePhotoUrl: null },
  { id: '5', fullName: 'Eva Martinez', email: 'eva@example.com', phone: '555-0105', city: 'Austin', state: 'TX', bio: 'Recent CS graduate.', skills: ['html', 'css', 'javascript'], experienceYears: 0, education: 'BS CS, UT Austin 2024', profilePhotoUrl: null }
]

export const getCompanyJobs = (companyId) => JOBS.filter(j => j.companyId === companyId)
export const getJobWithCompany = (jobId) => ({ ...JOBS.find(j => j.id === jobId), company: COMPANIES.find(c => c.id === JOBS.find(j => j.id === jobId)?.companyId) })
export const getFeaturedJobs = () => JOBS.slice(0, 6)
export const getAllJobs = () => JOBS
export const getCompanies = () => COMPANIES
export const getAllCandidates = () => CANDIDATES
export const getCandidate = (id) => CANDIDATES.find(c => c.id === id)